name: Build APK

on:
  push:
    branches:
      - "master"
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Build Tools
        run: sdkmanager "build-tools;34.0.0"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install buildozer and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y -V ca-certificates lsb-release
          sudo apt-get install -y -V git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses-dev cmake libffi-dev
          pip install --upgrade pip
          pip install buildozer cython==0.29.32

      - name: Build with buildozer
        run: |
          buildozer android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ExtroNorver-APK
          path: bin/*.apk
