name: Build APK

on:
  push:
    branches:
      - "master"
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y -V git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses-dev cmake libffi-dev

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.32

      - name: Manually set up Android SDK
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
          mkdir -p $ANDROID_HOME
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_HOME
          mv $ANDROID_HOME/cmdline-tools $ANDROID_HOME/cmdline-tools-old
          mkdir -p $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools-old/cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest
          rm -rf $ANDROID_HOME/cmdline-tools-old cmdline-tools.zip
          echo "y" | sdkmanager "platforms;android-34"
          echo "y" | sdkmanager "build-tools;34.0.0"
          echo "y" | sdkmanager "platform-tools"
          yes | sdkmanager --licenses

      - name: Build with buildozer
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
          buildozer android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ExtroNorver-APK
          path: bin/*.apk
